Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pycse import regress

p, pint, se = regress(X, Ca, 0.05)
print(p)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[9], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpycse[39;00m [38;5;28;01mimport[39;00m regress
[1;32m      3[0m p, pint, se [38;5;241m=[39m regress(X, Ca, [38;5;241m0.05[39m)
[1;32m      4[0m [38;5;28mprint[39m(p)

File [0;32m/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycse/__init__.py:24[0m
[1;32m     12[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mPYCSE[39;00m [38;5;28;01mimport[39;00m (
[1;32m     13[0m     polyfit,
[1;32m     14[0m     regress,
[0;32m   (...)[0m
[1;32m     20[0m     lbic,
[1;32m     21[0m )
[1;32m     22[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m [38;5;28;01mimport[39;00m feq, flt, fgt, fle, fge, read_gsheet
[0;32m---> 24[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mhashcache[39;00m [38;5;28;01mimport[39;00m hashcache
[1;32m     26[0m [38;5;66;03m# from .beginner import *[39;00m
[1;32m     29[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m [38;5;28;01mimport[39;00m get_ipython

File [0;32m/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycse/hashcache.py:48[0m
[1;32m     46[0m [38;5;28;01mimport[39;00m [38;5;21;01mfunctools[39;00m
[1;32m     47[0m [38;5;28;01mimport[39;00m [38;5;21;01minspect[39;00m
[0;32m---> 48[0m [38;5;28;01mimport[39;00m [38;5;21;01mjoblib[39;00m
[1;32m     49[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[1;32m     50[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpathlib[39;00m [38;5;28;01mimport[39;00m Path

[0;31mModuleNotFoundError[0m: No module named 'joblib'

